## Numpy Indexing & Slicing

In [1]:
a_list = [[1,2,3], ['a', 'b', 'c']]
a_list[1][1]

'b'

In [6]:
import numpy as np
a_arr = np.array([[1,2,3], [4,5,6]])
a_arr[1][1]

5

In [7]:
a_arr[1,1] ## 행(row) 열(column) , 리스트는 이렇게 못 불러냄 

5

### slicing

In [8]:
a = np.array([[1,2,3,4], [5, 6,7,8], [9, 10, 11, 12]], int)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[:2,:2]

array([[1, 2],
       [5, 6]])

In [10]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [14]:
a[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [17]:
a[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [19]:
a[1:,::2]

array([[ 5,  7],
       [ 9, 11]])

In [20]:
a[:1,::2]

array([[1, 3]])