## Numpy Comparison

In [1]:
import numpy as np 

In [2]:
### All & Any   ALL - AND , ANY - OR 

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [5]:
np.any(a>5)

True

In [6]:
np.all(a>5)

False

In [7]:
np.any(a>20), np.all(a<20)

(False, True)

### logical operation 

In [9]:
a = np.array([1, 3, 0], float)
b = np.logical_and(a>0, a<3) # 0 < a < 3
a
b

array([ True, False, False])

In [11]:
c = np.logical_or(a<0, a>3) # a < 0 or a > 3
c

array([False, False, False])

In [12]:
np.where(a > 0)  ## 조건을 만족하는 값의 인덱스를 줌 

(array([0, 1], dtype=int64),)

In [16]:
## Nan --> not a number, np.NaN 
## Inf --> Inifinite, np.Inf 무한대값 
x = np.array([1, np.NaN, np.Inf])
x 

array([ 1., nan, inf])

In [17]:
np.isnan(x)

array([False,  True, False])

In [18]:
len(x)

3

In [19]:
np.isnan(x).sum()

1

In [20]:
X = np.arange(1000, dtype=np.float32)
X[500] = np.NaN
np.isnan(X).sum()

1

In [21]:
np.isfinite(x)

array([ True, False, False])

In [22]:
len(x) - np.isfinite(x).sum()

2

### argmax & argmin 최대값 또는 최소 값이 있는 곳의 인덱스

In [24]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [25]:
np.argmax(a), np.argmin(a)

(5, 0)

In [28]:
a = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 8, 78, 23,  3]])

In [29]:
np.argmax(a, axis=0)

array([1, 1, 2, 1], dtype=int64)

In [30]:
np.argmin(a, axis=1)

array([0, 2, 3], dtype=int64)

In [31]:
np.max(a)

88