In [6]:
import numpy as np

In [9]:
# 1 
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 2
np.sort(vec)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
# 3
np.eye(1,10, k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [15]:
# 4
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# 5
x = [1,2,0,0,4,0]


TypeError: '>' not supported between instances of 'list' and 'int'